version: 2.1
jobs:
  build-and-test:
    docker:
      - image: markhobson/maven-chrome:latest
    steps:
      - checkout
      - run:
          name: Download Chromedriver
          command: sh downloadChromeDriver.sh linux64
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test -DbrowserOptions=headless
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/junitreports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results

workflows:
  sample:
    jobs:
      - build-and-test
