version: 2.1
jobs:
  build-and-test:
    docker:
      - image: markhobson/maven-chrome:latest
    steps:
      - checkout
      - download_webdriver:
          name: Download Chromedriver
          command: sh downloadChromeDriver.sh linux64
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test -DbrowserOptions=headless

workflows:
  sample:
    jobs:
      - build-and-test
